language: rust
rust:
  - 1.0.0
  - 1.1.0
  - beta
  - nightly
  - stable
matrix:
    allow_failures:
      rust: nightly
branches:
  - only:
      - master
      - develop
      - /^feature-.*$/
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a01dbbba8dcad4b82db8
    on_success: change
    on_failure: always
    on_start: always
  slack:
    secure: cjpZPOmM9uJNyOTd09fTcT7cMoghjOc4Qiu3hThU8XhkAJ5rkUZWaXKGpiSoCM1+7t9MM3DtnFa91KNOSPPjb+OoJNrr54+RNbLUT16OIYxzynbPSQxYWJ4osqrpoLImerSjW3JQsgKsj+eWTp442OkizJsxFkAsBmPIOAh1NsA=
