language: cpp
compiler:
  - clang
  - gcc

branches:
  only:
    - develop
    - testing

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt4-dev-tools libqt4-dev
  - ./test/build_deps.sh

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug

script: make

notifications:
  email:
    - jacky.alcine@thesii.org
  on_success: change
  on_failure: always
