---
- name: Check if we've already installed CMake.
  stat: >
    path=/usr/local/bin/cmake
  register: cmake_exec

- name: Check if we've downloaded the tarball for CMake already.
  stat: >
    path="/tmp/cmake-{{cmake_version}}.tar.gz"
  register: cmake_tarball
  when: cmake_exec.stat.exists == false

- name: Download tarball for CMake.
  get_url: >
    url="http://www.cmake.org/files/v2.8/cmake-{{cmake_version}}.tar.gz"
    dest="/tmp/cmake-{{cmake_version}}.tar.gz"
  when: cmake_exec.stat.exists == false and cmake_tarball.stat.exists == false

- name: Check if the tarball's been extracted already.
  stat: >
    path="/tmp/cmake-{{cmake_version}}"
  register: cmake_extracted
  when: cmake_exec.stat.exists == false

- name: Extract the tarball.
  command: "tar -xzf /tmp/cmake-{{cmake_version}}.tar.gz"
  args:
    chdir: /tmp
  when: cmake_exec.stat.exists == false and cmake_extracted.stat.exists == false

- name: Configure CMake for the local environment.
  command: ./configure --prefix=/usr/local
  args:
    chdir: "/tmp/cmake-{{cmake_version}}"
  when: cmake_exec.stat.exists == false

- name: Compile CMake.
  command: make -j4
  args:
    chdir: "/tmp/cmake-{{cmake_version}}"
  when: cmake_exec.stat.exists == false

- name: Install CMake.
  command: make install
  args:
    chdir: "/tmp/cmake-{{cmake_version}}"
  when: cmake_exec.stat.exists == false
