---
- name: compilers | Install clang
  apt: >
    name={{ item }}
    state=present
  when: compiler_family == "clang"
  register: compiler_install_clang
  with_items:
    - clang-3.6

- name: compilers | Set clang++-3.6 as the default C++ compiler.
  shell: |
    update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-3.6 10;
    update-alternatives --set c++ /usr/bin/clang++-3.6;
  when: compiler_family == "clang" and compiler_install_clang.changed == true

- name: compilers | Install gcc
  apt: >
    name={{ item }}
    state=present
  when: compiler_family == "gcc"
  register: compiler_install_gcc
  with_items:
    - g++-4.9
    - gcc-4.9
    - libgcc-4.9-dev

- name: compilers | Set g++-4.9 as the default C++ compiler.
  shell: |
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 10;
    update-alternatives --set g++ /usr/bin/g++-4.9;
  when: compiler_family == "gcc" and compiler_install_gcc.changed == true
