---
- include: ppa.yml tags=ppa,packages

- name: Update system package cache.
  apt: >
    update_cache=yes
    cache_valid_time=14400

- name: Upgrade system packages.
  apt: >
    upgrade=yes

- name: Install base tooling and Git.
  apt: >
    state=present
    name={{ item }}
  with_items:
    - libtool
    - automake
    - autoconf
    - bison
    - pkg-config
    - git
    - python-pip

- name: Install 'coveralls' client package.
  pip: >
    name={{ item }}
    state=present
  with_items:
    - coveralls

- name: Install dependencies for Wintermute.
  apt: >
    state=present
    name={{ item }}
  with_items:
    - libjsoncpp-dev
    - liblog4cxx10-dev
    - libconfig*-dev
    - uuid-dev
    - libzmq-dev

# We're going to build and install ZeroMQ ourselves because the version we're
# going to build with doesn't exist on Precise.
# TODO: Flesh out build setup for libzmq.
# TODO: Flesh out build setup for zmqpp.
#- include: zeromq.yml   tags=packages,zeromq

- name: Install test and documenation dependencies for Wintermute
  sudo: True
  apt: >
    state=present
    name={{ item }}
  with_items:
    - doxygen
    - cxxtest
    - valgrind
    - lcov

- include: cmake.yml      tags=packages,cmake
- include: uv.yml         tags=packages,uv
- include: libconfig.yml  tags=packages,libconfig
