---
- include: ppa.yml tags=ppa,packages

- name: Update system package cache.
  apt: >
    update_cache=yes
    cache_valid_time=14400

- name: Install base tooling and Git.
  apt: >
    state=latest
    name={{ item }}
  with_items:
    - libtool
    - automake
    - autoconf
    - bison
    - pkg-config
    - git
    - python-pip
    - binutils
    - libboost-program-options-dev

- include: compilers.yml tags=packages,compilers,gcc,clang

- name: Install 'coveralls' client package.
  pip: >
    name={{ item }}
    state=present
  with_items:
    - coveralls

- name: Install dependencies for Wintermute.
  apt: >
    state=latest
    name={{ item }}
  with_items:
    - libjsoncpp-dev
    - liblog4cxx10-dev
    - libzmq3-dev

- name: Install test and documenation dependencies for Wintermute
  sudo: True
  apt: >
    state=latest
    name={{ item }}
  with_items:
    - doxygen
    - cxxtest
    - valgrind
    - lcov

- include: cmake.yml      tags=packages,cmake
- include: uv.yml         tags=packages,uv
- include: libconfig.yml  tags=packages,libconfig
- include: zmqpp.yml      tags=packages,zmq,zmqpp
